"""add patient fields and appointments table

Revision ID: 65c6c10568d7
Revises: b6a3282b18bb
Create Date: 2025-12-18 23:56:26.015246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c6c10568d7'
down_revision: Union[str, Sequence[str], None] = 'b6a3282b18bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=False),
    sa.Column('is_new_patient', sa.Boolean(), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('doctor_name', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.add_column('patients', sa.Column('condition', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('blood_type', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('seizure_frequency', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('medication', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('guardian', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('contact', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'contact')
    op.drop_column('patients', 'guardian')
    op.drop_column('patients', 'medication')
    op.drop_column('patients', 'seizure_frequency')
    op.drop_column('patients', 'blood_type')
    op.drop_column('patients', 'condition')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
