"""fix eeg data table patient id

Revision ID: f831fd579b10
Revises: e4918a3dd461
Create Date: 2025-06-22 15:15:53.046314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f831fd579b10'
down_revision: Union[str, Sequence[str], None] = 'e4918a3dd461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notable_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notable_sessions_id'), 'notable_sessions', ['id'], unique=False)
    op.add_column('eeg_data', sa.Column('patient_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('eeg_data_time_idx'), table_name='eeg_data')
    op.drop_constraint(op.f('eeg_data_session_id_fkey'), 'eeg_data', type_='foreignkey')
    op.create_foreign_key(None, 'eeg_data', 'patients', ['patient_id'], ['id'])
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_column('eeg_data', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eeg_data', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'eeg_data', type_='foreignkey')
    op.create_foreign_key(op.f('eeg_data_session_id_fkey'), 'eeg_data', 'sessions', ['session_id'], ['id'])
    op.create_index(op.f('eeg_data_time_idx'), 'eeg_data', [sa.literal_column('time DESC')], unique=False)
    op.drop_column('eeg_data', 'patient_id')
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('sessions_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_pkey'))
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.drop_index(op.f('ix_notable_sessions_id'), table_name='notable_sessions')
    op.drop_table('notable_sessions')
    # ### end Alembic commands ###
